on: [push]

name: 'Build: GNU + Linux (ARM64)'

jobs:
  linux_aarch64:
    name: GNU + Linux (ARM64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-unknown-linux-gnu
          default: true
          profile: minimal
      - name: Build odo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target aarch64-unknown-linux-gnu
      - name: Prepare odo for upload
        run: |
          cd ./target/aarch64-unknown-linux-gnu/release/
          strip -v --strip-all ./libodo.a
          chmod +x ./odo
          tar -cvf aarch64-odo.gnu+linux.tar \
          odo \
          libodo.so \
          libodo.a
      - name: Upload odo build artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: aarch64-odo.gnu+linux
          path: ./target/aarch64-unknown-linux-gnu/release/aarch64-odo.gnu+linux.tar
          if-no-files-found: error
