on: [push]

name: 'Build: macOS (ARM64)'

jobs:
  mac_aarch64:
    name: macOS (ARM64)
    runs-on: macos-11
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-apple-darwin
          default: true
          profile: minimal
      - name: Build odo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target aarch64-apple-darwin
      - name: Prepare odo for upload
        run: |
          cd ./target/aarch64-apple-darwin/release/
          strip ./odo
          chmod +x ./odo
          tar -cvf aarch64-odo.osx.tar \
          odo \
          libodo.dylib \
          libodo.a
      - name: Upload odo build artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: aarch64-odo.osx
          path: ./target/aarch64-apple-darwin/release/aarch64-odo.osx.tar
          if-no-files-found: error
