on:
  push:
    branches:    
      - 'master'

name: 'Build: macOS (x86_64)'

jobs:
  mac_x86-64:
    name: macOS (x86_64)
    runs-on: macos-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
          default: true
          profile: minimal
      - name: Build odo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target x86_64-apple-darwin
      - name: Prepare odo for upload
        run: |
          cd ./target/x86_64-apple-darwin/release/
          strip ./odo
          chmod +x ./odo
          tar -cvf x86_64-odo.osx.tar \
          odo \
          libodo.dylib \
          libodo.a
      - name: Upload odo build artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-odo.osx
          path: ./target/x86_64-apple-darwin/release/x86_64-odo.osx.tar
          if-no-files-found: error