on: [push]

name: 'Build: Windows (x86_64)'

jobs:
  windows_x86-64:
    name: Windows (x86_64)
    runs-on: windows-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-gnu
          target: x86_64-pc-windows-gnu
          default: true
          profile: minimal
      - name: Build odo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target x86_64-pc-windows-gnu
      - name: Prepare odo for upload
        run: |
          cd ./target/x86_64-pc-windows-gnu/release/
          tar -czvf x86_64-odo.win32.zip `
          odo.exe `
          odo.dll `
          libodo.a `
          libodo.dll.a
      - name: Upload odo build artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-odo.win32
          path: ./target/x86_64-pc-windows-gnu/release/x86_64-odo.win32.zip
          if-no-files-found: error