on:
  push:
    branches:    
      - 'master'

name: 'Build: GNU + Linux (x86_64)'

jobs:
  linux_x86-64:
    name: GNU + Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          default: true
          profile: minimal
      - name: Build odo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target x86_64-unknown-linux-gnu
      - name: Prepare odo for upload
        run: |
          cd ./target/x86_64-unknown-linux-gnu/release/
          strip -v --strip-all ./odo
          strip -v --strip-all ./libodo.so
          strip -v --strip-all ./libodo.a
          chmod +x ./odo
          tar -cvf x86_64-odo.gnu+linux.tar \
          odo \
          libodo.so \
          libodo.a
      - name: Upload odo build artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-odo.gnu+linux
          path: ./target/x86_64-unknown-linux-gnu/release/x86_64-odo.gnu+linux.tar
          if-no-files-found: error